### ISSUE TITLE
Question regarding MonthDayPartialRange

### ISSUE THREAD

**Issue by gembin** [clulab/timenorm#23]
class `MonthDayPartialRange` in `TemporalFields.scala`
```scala
 private val sizes = for (year <- Set(1999, 2000)) yield {
    this.addToSize(LocalDate.of(year, 1, 1), +1L)
  }
```
I'm quite confused,  why a fixed year `Set(1999, 2000)`?    i'm from java background not sure if i understand correctly

**Comment by bethard** [comment]
This is used only to fill in the required `range` attribute, which is supposed to say how many days an instance of the field might be. In the case of `MonthDayPartialRange`, the number of days will always be the same, except possibly on a leap year. So I've arbitrarily taken one non-leap year (1999) and one leap year (2000) and used them to measure how long the `MonthDayPartialRange` might be. That defines the `min` and `max` needed in the next line.

**Comment by gembin** [comment]
Thanks for your detailed explanation.

I tried to understand it in java way.  what's the return type of `private val sizes`,  `Set`?   and where are`sizes.min and sizes.max` from?
```java
long size1= addToSize(LocalDate.of(1999, 1, 1), +1L);
long size1= addToSize(LocalDate.of(2000, 1, 1), +1L);
long min= Math.min(size1, size2);  
long max= Math.max(size1, size2);  
```
is it correct?

**Comment by bethard** [comment]
Yes, that's correct. The type of `sizes` should be a `Set[Long]`, and the min and max are doing essentially what you do in your code.

**Comment by gembin** [comment]
Thanks!
