### ISSUE TITLE
Hangs

### ISSUE THREAD

**Issue by kwalcock** [clulab/timenorm#54]
This will be difficult to figure out.  Maybe I can isolate the text some more.  I haven't been able to reproduce the problem in a simpler environment, even with the complete text.

TimeNormFinder is hanging on line 208  : `case timeInterval: TimExInterval if timeInterval.isDefined =>` when timeInterval is
```
LastRI(ThisRI(LastRI(SimpleInterval(2012-01-31T00:00,2012-02-01T00:00),RepeatingField(MonthOfYear,1,None,Some((163,170))),<function1>,Some((163,170))),IntersectionRI(Set(RepeatingField(DayOfMonth,30,None,Some((160,162))), RepeatingField(org.clulab.time.EVENING_OF_DAY$@e4271e5,1,None,Some((172,179)))),None),Some((153,158))),RepeatingField(DayOfWeek,1,None,Some((152,158))),<function1>,Some((152,153)))
```
I'm running ExtractDartMetaFromDirectory in the DART4-42k-B branch with these two files: 
[5cf45425e8a195fe5bb6c61222cd529f.txt](https://github.com/clulab/timenorm/files/3962336/5cf45425e8a195fe5bb6c61222cd529f.txt)
[5cf45425e8a195fe5bb6c61222cd529f.json.txt](https://github.com/clulab/timenorm/files/3962341/5cf45425e8a195fe5bb6c61222cd529f.json.txt)

The latter file may need .txt removed before it can be used.

**Comment by bethard** [comment]
@EgoLaparra Looks like the expression there is:
```
LastRI(
  ThisRI(
    LastRI(
      SimpleInterval.of(2012, 1, 31),
      RepeatingField(MONTH_OF_YEAR, 1)),
    IntersectionRI(Set(
      RepeatingField(DAY_OF_MONTH, 30),
      RepeatingField(org.clulab.time.EVENING_OF_DAY, 1)))),
  RepeatingField(DAY_OF_WEEK, 1))
```
And it's the `ThisRI` that's causing the problem:
```
scala> import org.clulab.timenorm.scate._; import org.clulab.time._; import java.time.temporal.ChronoField._; import java.time.temporal.ChronoUnit._
import org.clulab.timenorm.scate._
import org.clulab.time._
import java.time.temporal.ChronoField._
import java.time.temporal.ChronoUnit._

scala> ThisRI(SimpleInterval.of(2011, 1), IntersectionRI(Set(RepeatingField(DAY_OF_MONTH, 30), RepeatingField(EVENING_OF_DAY, 1)))).start
% hangs
```
Must be something wrong with our implementation of `ThisRI` somewhere in:
https://github.com/clulab/timenorm/blob/master/src/main/scala/org/clulab/timenorm/scate/Types.scala#L314

**Comment by EgoLaparra** [comment]
I've been exploring this error briefly and I think the problem is in `IntersectionRI`, but I'm not sure yet.

**Comment by bethard** [comment]
Yes, if you use either of the things within the `IntersectionRI` instead, you do not get an error. So it's definitely in the interaction between `ThisRI` and `IntersectionRI`.

**Comment by EgoLaparra** [comment]
This seems to be caused by a misalignment of `firstInterval` and `startPoint` in the `following ` function of `IntersectionRI`. 
https://github.com/clulab/timenorm/blob/2ea4c4a9afd9495de2b07a9e6664ee8c784a03db/src/main/scala/org/clulab/timenorm/scate/Types.scala#L838-L856

`firstInterval` gets the value from an iterator of following `RepeatingInterval`s. For `RepeatingField(DAY_OF_MONTH, 30)`, this will skip "February", but `startPoint` won't because we always add a single month (in this case) to its value. From this point on, all the values in `othersBeforeStart` are before `firstInterval` and, thus, `Iterator.continually` always returns nil. Something like:
```
 do {
        startPoint = startPoint.plus(1, range)
 } while(startPoint isBefore firstInterval.end)
``` 
solves the error found by @kwalcock, but I'm not sure if this is a good solution.

**Comment by bethard** [comment]
I'm not sure about the condition on your proposed `while`. If the problem is that nothing is before the start, maybe check everything, not just the `firstInterval`? Something like:
```
do {
    startPoint = startPoint.plus(1, range)
} while (iterators.exists(_.head.end isBefore startPoint))
```
Please make sure that when you try out these changes you (1) write some tests that currently hang but are fixed by your changes and (2) apply the same fix to `preceding` and `following` since they almost certainly are vulnerable to the same bug.

**Comment by EgoLaparra** [comment]
I'm a bit confused about that code. In:
https://github.com/clulab/timenorm/blob/2ea4c4a9afd9495de2b07a9e6664ee8c784a03db/src/main/scala/org/clulab/timenorm/scate/Types.scala#L870
The intervals in `iterator.tail` are retrieved while `it.head.end isBefore startPoint`. In the next iteration of `Iterator.continually` we add a month to `startPoint`, so `iterators.tail.end.head` will always be before `startPoint`, right?

**Comment by kwalcock** [comment]
I'm glad to see that you're getting closer.

**Comment by bethard** [comment]
I believe the goal of this code was to take each of the iterator objects in `iterators` and peel off all intervals within each that are before `startPoint`, without removing any intervals that were not from the iterator objects. I think it was bending over backwards to try not to drop the failed element It's quite possible that it doesn't correctly achieve that. ;-)

After looking at [this stackoverflow answer](https://stackoverflow.com/questions/47717671/scala-iterator-takewhile-is-dropping-the-failed-element), maybe we should instead be doing something like (untested):
```
    var iterators = sortedRepeatingIntervals.map(_.following(startPoint).buffered)

    Iterator.continually {
      do {
        startPoint = startPoint.plus(1, range)
      } while (!iterators.exists(_.head.end isBefore startPoint))
      val firstInterval = iterators.head.next
      val tup = iterators.tail.map(_.span(_.end isBefore startPoint)).unzip
      val othersBeforeStart = tup._1
      iterators = tup._2
```
That is, use `.span` and then reassign `iterators` to the second values returned by `.span`.

**Comment by EgoLaparra** [comment]
I've added the code with a few changes and opened a new pull-request: https://github.com/clulab/timenorm/pull/57

**Comment by EgoLaparra** [comment]
This is solved in https://github.com/clulab/timenorm/pull/57
