### ISSUE TITLE
Need speed

### ISSUE THREAD

**Issue by kwalcock** [clulab/timenorm#63]
Heads up!  We may be discussing this soon.

Component | Time (ms)
-- | --
Distinct | 3
MigrationHandler | 6
NegationHandler | 21
StopwordManager | 35
ConceptExpander | 43
HedgingHandler | 77
Actions | 91
NestedArgumentExpander | 103
Processors | 196
GazetteerEntityFinder | 342
OntologyHandler | 410
RuleBasedEntityFinder | 783
GeoNormFinder | 12450
TimeNormFinder | 697795

Component | Time (ms)
-- | --
Distinct | 21
MigrationHandler | 22
HedgingHandler | 88
StopwordManager | 159
ConceptExpander | 296
Actions | 430
NegationHandler | 524
Processors | 670
NestedArgumentExpander | 1073
OntologyHandler | 2484
RuleBasedEntityFinder | 3132
GazetteerEntityFinder | 12086
GeoNormFinder | 98933
TimeNormFinder | 1624415

**Comment by bethard** [comment]
Please file this issue in Eidos, rather than timenorm, and assign @EgoLaparra and @bethard there.

**Comment by kwalcock** [comment]
Moved to https://github.com/clulab/eidos/issues/800.
