### ISSUE TITLE
License for the timenorm code

### ISSUE THREAD

**Issue by bhuthesh** [clulab/timenorm#66]
Hi, I wanted to use the timenorm code for some experimentation. While there is no license file at the top level in the repo, I see you have mentioned  license as Apache 2 in the build.sbt file. Is the whole repo licensed under Apache 2?

**Comment by bethard** [comment]
Indeed, everything is Apache 2. Thanks for pointing out that the license file was missing.

**Comment by bhuthesh** [comment]
Thanks a lot for the quick resolution.
